[package]
name = "minecraft-backup-manager"
version = "0.0.0"
edition = "2018"
authors = ["Xendergo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
